on:
  workflow_dispatch:
    inputs:
      tags:
        description: 'Test scenario tags'
        required: true
        type: string
      
  # push:
  #   branches:
  #     - main
name: deploy-waxz/lobe-chat
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    permissions:
      contents: read
      deployments: write
    steps:
    - name: Print the input tag to STDOUT
      run: echo  The tags are ${{ inputs.tags }} 
    - uses: actions/checkout@master
      with:
          repository: waxz/lobe-chat
          path: ./lobe-chat
          submodules: recursive
          ref: ${{ inputs.tags }}
    - uses: actions/setup-node@v5
      with:
          node-version: 22
    - name: Setup Bun
      uses: oven-sh/setup-bun@v1 # Use the latest stable version
    - name: Install Vercel CLI
      run: |
          #npm install --global vercel@43.3.0
          bun add -g vercel@latest
    - name: Pull Vercel Environment Information
      run: |
          cd ./lobe-chat
          vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
    - name: Build Project Artifacts
      run: |
          cd ./lobe-chat
          vercel build --token=${{ secrets.VERCEL_TOKEN }}
    - name: Deploy Project Artifacts to Vercel
      run: |
          cd ./lobe-chat
          vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }} --archive=tgz
          # vercel --prod --token=${{ secrets.VERCEL_TOKEN }} --archive=tgz
