on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main
name: deploy-waxz/lobe-chat
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    permissions:
      contents: read
      deployments: write
    steps:
    - uses: actions/checkout@master
      with:
          repository: waxz/lobe-chat
          path: ./lobe-chat
          submodules: recursive

    - name: Setup Bun
      uses: oven-sh/setup-bun@v1 # Use the latest stable version

    - name: Install Vercel CLI
      run: |
          cd ./lobe-chat
          npm install --global vercel@latest
    - name: Pull Vercel Environment Information
      run: |
          cd ./lobe-chat
          vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
    - name: Build Project Artifacts
      run: |
          cd ./lobe-chat
          vercel build --token=${{ secrets.VERCEL_TOKEN }}
    - name: Deploy Project Artifacts to Vercel
      run: |
          cd ./lobe-chat
          vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
